version: "3.9"

services:
  redis:
    image: redis:7
    container_name: fhamb_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - fhamb_net

networks:
  fhamb_net:
    external: true
