version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: fhamb-be:latest
    container_name: fhamb_app
    ports:
      - "8080:8080"
    env_file:
      - /root/pubserver/.env.prod 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - fhamb_net

networks:
  fhamb_net:
    external: true
