services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot_certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"

volumes:
  certbot_certs:
