name: Docker Compose Up

on:
  push:
    branches:
      - main

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Docker Compose
        run: docker compose --env-file .env -f docker/dev-docker-compose.yml up -d --build
